# Introduction

According to NumPy's official description:
> NumPy is the fundamental package for scientific computing with Python.

And, among other things, it provides the following (taken from the docstring):

* An array object of arbitrary homogeneous items
* Fast mathematical operations over arrays
* Linear Algebra, Fourier Transforms, Random Number Generation

By convention, NumPy is usually imported as **np**:

In [1]:
import numpy as np
np.__version__

'1.18.1'

As usual, IPython provides quick access to the package's documentation (docstring) with the use of '?':

In [2]:
np?

To better understand the benefits of NumPy-style arrays, one must first understand how Python lists work.

Although the two lists below might appear to be different, since one contains only integer values whilst the other has a mixture of types, they are both, in essence, the same.

Since each value in Python is more like a full-fledged object than a primitive type like those of the C programming language (because of Python's dynamic types), they hold a lot of information that can cause some overhead.

In [3]:
heterogeneous = ["string", True, 88, 3.14]
homogeneous = list(range(4))
# The folowing works because homogeneous is not only a list of integers, but a dynamic list like any other
homogeneous.append("hello")

## Creating NumPy arrays

Although Python provides the built-in array module to get rid of that overhead providing true homogeneous structures, NumPy extends on that providing efficient operations to be performed on the data.

### Deriving Arrays from Lists
The following are examples of NumPy arrays derived from Python's lists.

In [4]:
# Type infered since all items are integers 
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
# Integers are converted to floats so that the list can be homogeneous
np.array([3.14, 1, 2, 3, 4]) 

array([3.14, 1.  , 2.  , 3.  , 4.  ])

In [6]:
# Everything is now a string of characters to obey the homogeneity restrictions
np.array(["string", 3.14, 1, 2, 3, 4]) 

array(['string', '3.14', '1', '2', '3', '4'], dtype='<U6')

The `dtype` keyword allows us to specify the type of the resulting array:

In [7]:
np.array([4, 3, 2, 1], dtype='float32')

array([4., 3., 2., 1.], dtype=float32)

In [8]:
# 3.14 converted to a integer
np.array([3.14, 2, 1], dtype='int_') 

array([3, 2, 1])

In [9]:
# Nested lists result in multi-dimensional arrays
np.array([[7, 8, 9], [4, 5, 6], [1, 2, 3]])

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

### Creating Arrays from scratch

This method is more efficient, although this is mostly noticeable for large arrays

In [10]:
# Creates an array of length 10 filled with zeroes
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# Creates an array of dimensions 3x5 filled by ones (in this case the variables are flaoting-points)
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Creates an array with the dimensions specified by the first argument, and fills it with the value of the second
np.full(10, 42)

array([42, 42, 42, 42, 42, 42, 42, 42, 42, 42])

In [13]:
# Creates an array filled with a linear sequence starting from 0, up to 8 (not inclusive) stepping by 2
# When omitted, the step parameter defaults to 1
np.arange(0, 8, 2)

array([0, 2, 4, 6])

In [14]:
# Creates an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.49818423, 0.51915767, 0.07105887],
       [0.46085089, 0.02289726, 0.67892545],
       [0.33105929, 0.11167796, 0.85221397]])

In [16]:
# 3x3 array of normally distributed (Gaussian distribution) values where the mean is 0 and std dev is 1
np.random.normal(0, 1, (3,3))

array([[ 0.33038854,  0.63022132, -0.63137653],
       [ 0.14337353,  1.02085212, -1.75704747],
       [ 0.41464427, -2.19481296, -0.00641442]])

In [17]:
# Array of length 5 of random integers between 0 and 10
np.random.randint(0, 10, 5)

array([0, 9, 1, 4, 9])

In [18]:
# Creates a 5x5 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# Creates an array of length 15 of uninitialized values
# The values will be whatever happens to be at the memory address before memory allocation takes place
np.empty(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### NumPy Standard Data Types

The standard NumPy data types can be referred to through the use of a specified string:

In [20]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

Or using the associated NumPy object:

In [21]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

NumPy standard data types can be found on [this](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html#NumPy-Standard-Data-Types) section of the handbook or, evidently, on the [NumPy documentation](https://numpy.org/)