# Broadcasting

Another way to vectorize operations is using NumPy's broadcasting functionality. Broadcasting is a set of rules for applying binary ufuncs (e.g addition and subtractions) on arrays of different sizes.

In [1]:
import numpy as np
a = np.array([0, 1, 2])
a + 5

array([5, 6, 7])

Although 5 is no more than a integer value, NumPy treats it like an array of the same length of `a`, filled with the value 5. Therefore, an element by element addition is performed, just like it would with the usage of ufuncs.

This also works for multi-dimensional arrays:

In [2]:
multi = np.ones((3,3))
a + multi

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

`a` is expanded to match the dimensions of `multi` so that the addition operation can take place. The next case expands both `a` and `b` to 3x3 matrices:

In [3]:
# Horizontal (1x3) array
a = np.arange(3)
# Vertical (3x1) array
b = np.arange(3)[:, np.newaxis]
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

When NumPy's broadcasting rules (depicted [here](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html#Rules-of-Broadcasting)) cannot reshape the arrays to a shape that is feasible to perform an operation, an error is thrown. The following is an example where broadcasting does not work:

In [4]:
M = np.ones((3, 2))
a = np.arange(3)
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 