# Comparisons

This notebook covers comparisons, and manipulation of arrays with masks.

Just like arithmetic operators, NumPy also implements all six comparisons operators as element-wise ufuncs.

In [1]:
import numpy as np
np.random.seed(0)
x = np.arange(5)

In [2]:
x < 3

array([ True,  True,  True, False, False])

In [3]:
x > 3

array([False, False, False, False,  True])

In [4]:
x >= 3

array([False, False, False,  True,  True])

In [5]:
x <= 3

array([ True,  True,  True,  True, False])

In [6]:
x != 3

array([ True,  True,  True, False,  True])

In [7]:
x == 3

array([False, False, False,  True, False])

It is also possible to do an element-wise comparison between arrays:

In [8]:
(2 * x) == (x ** 2)

array([ True, False,  True, False, False])

This feature can be taken advantage of for things like counting the amount of entries that satisfy some condition:

In [9]:
# np.count_nonzero counts how many entries are not zero (or, in this case, False)
print(np.count_nonzero(x < 3))
# np.sum sums all values of the array (True equals to 1 and False equals to 0)
print(np.sum(x < 3))

3
3


In [10]:
m = np.random.randint(10, size=(3,4))
# Counts number of elements lesser than 5 for each row
np.sum(m < 5, axis=1)

array([3, 1, 2])

It is also possible to verify if a given condition is true at least once with `np.any` or if it is always true with `np.all`

In [11]:
# Is there any element greater than 7?
np.any(m > 7)

True

In [12]:
# Are all elements lesser than 10?
np.all(m < 10)

True

Boolean arrays (such as comparisons results) can act as filters to select only particular data that match a given criteria:

In [13]:
m[m < 5]

array([0, 3, 3, 3, 2, 4])

One thing to note is that bitwise operations can be used to give more control over the results:

In [14]:
m[(m < 3) | (m > 6)]

array([0, 7, 9, 2, 7])