# Fancy Indexing

Fancy indexing consists of using an array of indices to access multiple array elements at once. For example:

In [1]:
import numpy as np
x = np.arange(1, 10)
indices = np.arange(1, 9, step=2)
x[indices]

array([2, 4, 6, 8])

One useful thing to know is that the result of fancy indexing reflects the shape of the index array

In [2]:
indices = np.array([[0, 1], [2, 3]])
x[indices]

array([[1, 2],
       [3, 4]])

An example with multi-dimensional arrays:

In [3]:
x = np.arange(12).reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
row = np.arange(3)
col = np.array([2, 1, 3])
x[row, col]

array([ 2,  5, 11])

In the next example some quite interesting happens. Broadcasting is performed so that `row[:, np.newaxis]` (a column vector) and `col` (a row vector) can match. This results in a two-dimensional array:

In [5]:
x[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

What happened is that each `row` value gets matched with each `col` value. The result is a tow-dimensional array as seen above.

Of course, fancy indexing is not limited to only reading array values, but also modifying them:

In [6]:
y = np.arange(10)
y[np.array([2, 1, 8, 4])] = 99
y

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])

A note on operations with repeated indices. One might expect that the resulting array will contain a couple of elements with the value `2` in it:

In [7]:
arr = np.zeros(10)
i = [2, 2, 3, 4, 5, 5]
arr[i] += 1
arr

array([0., 0., 1., 1., 1., 1., 0., 0., 0., 0.])

As demonstrated, this is not what actually happens. The reason for that is that we are actually assigning `x[i]` to `x[i] + 1` for each and every element of `i`. Since `arr` is an array of zeros, it doesn't matter if the index appears once or multiple times, the result will always be `1`.

If the desired behavior is to repeat the operation multiple times, the `at` method can be used to perform the operations in-place. That is, the values are always read before an operation to account for possible changes. 

In [8]:
arr = np.zeros(10)
np.add.at(arr, i, 1)
arr

array([0., 0., 2., 1., 1., 2., 0., 0., 0., 0.])

## Combined Indexing

What makes all these indexing options so powerful is the ability of combine them.

For instance, simple indices can be combined with fancy indexing:

In [9]:
# On the second row, values at the indeces [2, 0, 1]
x[2, [2, 0, 1]]

array([10,  8,  9])

The combination of slicing with fancy indexing also works:

In [10]:
# From the row 1 onwards, indeces [2, 0, 1]
x[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

At last, masking can also be combined with fancy indexing:

In [11]:
# Ones and zeros will be converted to Trues and Falses
mask = np.array([1, 0, 1, 0], dtype=bool)
x[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])