# Sorting NumPy Arrays

NumPy provides the `np.sort` function which defaults to _quicksort_ (which is an $O(N \log N)$ algorithm), though _mergesort_ and _heapsort_ can also be used. 

In [1]:
import numpy as np
np.random.seed(0)

In [2]:
x = np.arange(20)
np.random.shuffle(x)
# Returns a sorted array
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

`np.sort` does not perform in-place sorting, whereas the `sort` method does:

In [3]:
x

array([18,  1, 19,  8, 10, 17,  6, 13,  4,  2,  5, 14,  9,  7, 16, 11,  3,
        0, 15, 12])

In [4]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

`np.argsort` is a related function that returns the _indices_ of the sorted elements:

In [5]:
np.random.shuffle(x)
print(x)
np.argsort(x)

[11  1 18 17  2 12 19 16 10  0  3  4 15  8 13  9  5 14  7  6]


array([ 9,  1,  4, 10, 11, 16, 19, 18, 13, 15,  8,  0,  5, 14, 17, 12,  7,
        3,  2,  6])

For multidimensional arrays it is possible to specify wheter to sort along specific columns or rows:

In [6]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [7]:
# Sort each column individually
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [8]:
# Sort each row individually
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Partitioning

NumPy provides the `np.partition` function to find the $k$ smallest values in the array. The result is an array with the $k$ smallest values to the left of the array in arbitrary order:

In [9]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

As usual, the same operation can be performed in a multidimensional array along a given axis:

In [10]:
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

Just as there is a `np.argsort` there is also a `np.argpartition` function, with similar functionally, but for partitioning.